# Generated by Django 3.0.1 on 2020-01-14 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=64)),
                ('lang_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qb.Language'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qb.Language'),
        ),
    ]
