# Generated by Django 3.0.3 on 2020-02-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='standard',
        ),
    ]
