# Generated by Django 3.0.3 on 2020-02-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb', '0003_auto_20200226_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(),
        ),
    ]
