# Generated by Django 3.0.3 on 2020-04-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb', '0005_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='standard',
            field=models.ManyToManyField(to='qb.Standard'),
        ),
    ]
